version: '3.3'
services:
  web:
    build: .
    env_file: .env
    environment:
      - MIX_ENV=dev
      - PORT=4000
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
    environment:
     - POSTGRES_USER=${CODEBATTLE_DATABASE_USERNAME}
     - POSTGRES_PASSWORD=${CODEBATTLE_DATABASE_PASSWORD}
     - POSTGRES_HOST=${CODEBATTLE_DATABASE_HOSTNAME}

  test:
    build: .
    command: mix test
    env_file: .env
    environment:
      - MIX_ENV=test
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
   postgres-data:
     driver: local